#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_ROOT}"

mkdir -p Configs

: "${GOOGLE_OAUTH_KEY_DEV:?GOOGLE_OAUTH_KEY_DEV is not set}"
: "${GOOGLE_OAUTH_KEY_PROD:?GOOGLE_OAUTH_KEY_PROD is not set}"

cat > Configs/Secrets.xcconfig <<EOF
// Generated by Xcode Cloud at build time. Do not commit.
GOOGLE_OAUTH_KEY_DEV = ${GOOGLE_OAUTH_KEY_DEV}
GOOGLE_OAUTH_KEY_PROD = ${GOOGLE_OAUTH_KEY_PROD}
EOF

test -s Configs/Secrets.xcconfig
