#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_ROOT}"

mkdir -p Configs

: "${GOOGLE_OAUTH_KEY_DEV:?GOOGLE_OAUTH_KEY_DEV is not set}"
: "${GOOGLE_OAUTH_KEY_PROD:?GOOGLE_OAUTH_KEY_PROD is not set}"
: "${AMPLITUDE_API_KEY_DEV:?AMPLITUDE_API_KEY_DEV is not set}"
: "${AMPLITUDE_API_KEY_PROD:?AMPLITUDE_API_KEY_PROD is not set}"
: "${SUPPORT_EMAIL_DEV:?SUPPORT_EMAIL_DEV is not set}"
: "${SUPPORT_EMAIL_PROD:?SUPPORT_EMAIL_PROD is not set}"

google_scheme_dev="com.googleusercontent.apps.${GOOGLE_OAUTH_KEY_DEV%%.apps.googleusercontent.com}"
google_scheme_prod="com.googleusercontent.apps.${GOOGLE_OAUTH_KEY_PROD%%.apps.googleusercontent.com}"

cat > Configs/Secrets.xcconfig <<EOF
// Generated by Xcode Cloud at build time. Do not commit.
GOOGLE_OAUTH_KEY_DEV = ${GOOGLE_OAUTH_KEY_DEV}
GOOGLE_OAUTH_KEY_PROD = ${GOOGLE_OAUTH_KEY_PROD}
GOOGLE_OAUTH_REDIRECT_SCHEME_DEV = ${google_scheme_dev}
GOOGLE_OAUTH_REDIRECT_SCHEME_PROD = ${google_scheme_prod}
AMPLITUDE_API_KEY_DEV = ${AMPLITUDE_API_KEY_DEV}
AMPLITUDE_API_KEY_PROD = ${AMPLITUDE_API_KEY_PROD}
SUPPORT_EMAIL_DEV = ${SUPPORT_EMAIL_DEV}
SUPPORT_EMAIL_PROD = ${SUPPORT_EMAIL_PROD}
EOF

test -s Configs/Secrets.xcconfig
